app:
  port: 8880
  env: "dev" # 环境（dev/test/prod）
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 10
jwt:
  secret: "your-jwt-secret-key"
  access_expire: 7200 # 2小时
  refresh_expire: 604800 # 7天
log:
  level: "debug"
  enable_console: true
  filename: ""
  encoding: "console"
  enable_caller: true
  stacktrace_level: "error"